\connect bdd_project;

\! echo ""
\! echo ""
\! echo "-- REQ1: Récupérer le volume total d'une cargaison d'un navire (Requête qui porte sur au moins trois tables)"
\! echo ""
\i req/req1.sql;
\! echo ""
\! echo ""
\! echo ""
\! echo ""
\! echo "-- REQ2: Afficher le nom des nations en guerre (Auto-jointure)"
\! echo ""
\i req/req2.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ3: La liste des navires dont tout les port de pays de departs de leur voyages sont identiques a leur nationalités (sous-requête corrélée)"
\! echo ""
\i req/req3.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ4: La moyenne des passagers maximaux sur les voyages intercontinentaux (sous-requête dans le FROM)"
\! echo ""
\i req/req4.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ5: Toutes les bateaux de nations qui ne sont pas en guerres. (Sous-requête dans le WHERE)"
\! echo ""
\i req/req5.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ6: Les voyages qui comportent des produits périssables d''une valeur d''au moins 16€ le kilo."
\! echo ""
\i req/req6.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ7: Les ports où il y a toujours en moyenne moins de passagers sortant que arrivants (Requête statistiques)"
\! echo ""
\i req/req7.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ8: Nombre de produits dans une catégorie où la répartition des valeurs dans la catégorie est linéaire ou exponentielle (AVG() >= ((MAX() - MIN()) / 2) (Requête nécessitant GROUP BY et HAVING)"
\! echo ""
\i req/req8.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ9: Les navires dont tous les voyages ont au moins une étape (Condition de totalité)"
\! echo ""
\i req/req9.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ10: Moyenne des passagers maximums de tous les bateaux (toute nationalité confondue) (Requête nécessitant le calcul de 2 agrégats)"
\! echo ""
\i req/req10.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ11: Récupérer les voyages d''un navire (LEFT JOIN)"
\! echo ""
\i req/req11.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ12: Récupérer le parcours des bateaux (Requête récursive)"
\! echo ""
\i req/req12.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ13: Les bateaux qui ont touts leurs voyages intercontinentaux (Condition de totalité)"
\! echo ""
\i req/req13.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ14: Le nombre de passagers transportés vers chaque continents pour les voyages étant arrivés en 1754 (Requête de statistiques)"
\! echo ""
\! req/req14.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ15: La quantité totale de produits disponibles dans chaque ports trié par le port le plus important (Requête de statistiques)"
\! echo ""
\i req/req15.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ16: La nation qui a le plus de navires dont la catégorie est supérieure ou égale à 4 (Requête de statistiques)"
\! echo ""
\i req/req16.sql;
\! echo ""
\! echo "------------------------------------------------------------------------"
