\connect bdd_project;

\! echo ""
\! echo ""
\! echo "-- REQ1: Récupérer le volume total d'une cargaison d'un navire"
\! echo ""
\i req/req1.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ2: Afficher le nom des nations en guerre"
\! echo ""
\i req/req2.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ3: sous requete corrélére (La liste des navires dont tout les port de pays de departs de leur voyages sont identiques a leur nationalités)"
\! echo ""
\i req/req3.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ4: sous requete dans FROM"
\! echo ""
\i req/req4.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ5: sous requete dans WHERE"
\! echo ""
\i req/req5.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ6: Nombre de produits dans une catégorie où la répartition des valeurs dans la catégorie est linéaire ou exponentielle (AVG() >= ((MAX() - MIN()) / 2)"
\! echo ""
\i req/req6.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ7: Récupérer le volume total d'une cargaison d'un navire"
\! echo ""
\i req/req7.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ8: Récupérer le volume total d'une cargaison d'un navire"
\! echo ""
\i req/req8.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ9: Récupérer le volume total d'une cargaison d'un navire"
\! echo ""
\i req/req9.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ10: Moyenne des passagers maximums de tous les bateaux (toute nationalité confondue)"
\! echo ""
\i req/req10.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ11: Récupérer les voyages d'un navire"
\! echo ""
\i req/req11.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ12:Récupérer le parcours des bateaux"
\! echo ""
\i req/req12.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ13: Les bateaux qui ont touts leurs voyages intercontinentaux"
\! echo ""
\i req/req13.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ14: Le nombre de passagers transportés vers chaque continents pour les voyages étant arrivés en 1754"
\! echo ""
\i req/req14.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ15:  La quantité totale de produits disponibles dans chaque ports trié par le port le plus important"
\! echo ""
\i req/req15.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
\! echo ""
\! echo ""
\! echo "-- REQ16: La nation qui a le plus de navires dont la catégorie est supérieure ou égale à 4"
\! echo ""
\i req/req16.sql;
\! echo ""
\i echo "------------------------------------------------------------------------"
